- hosts: all
  become: yes
  roles:
    - common
- hosts: snapclients
  become: yes
  roles:
    - snapclient
    - raspotify
- hosts: snapservers
  become: yes
  roles:
    - snapserver
    - raspotify
    - nad-controller
- hosts: hass-servers
  become: yes
  roles:
    - hass
    - debmatic
    - mosquitto
    - deconz
- hosts: network-master
  become: yes
  roles:
    - unifi
    - samba
    - paperless-ngx

