- hosts: all
  become: yes
  roles:
    - common
- hosts: snapclients
  become: yes
  roles:
    - snapclient
    - raspotify
- hosts: snapservers
  become: yes
  roles:
    - snapserver
    - raspotify
- hosts: hass-servers
  become: yes
  roles:
    - hass


