- name: Ensure snapclient is downloaded
  get_url:
    url: https://github.com/badaix/snapcast/releases/download/v0.24.0/snapclient_0.24.0-1_armhf.deb
    dest: '/home/pi/snapclient_0.24.0-1_armhf.deb'
  register: downloaded_package
- name: Ensure snapclient is installed
  apt:
    deb: '{{downloaded_package.dest}}'
- name: Ensure snapclient service is enabled and started
  service:
    name: snapclient
    state: started
    enabled: yes
