- name: Ensure home assistant requirements are apt installed
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-pip

- name: Ensure home assistant requirements are pip installed
  ansible.builtin.pip:
    name:
      - docker

- name: Ensure docker service runs
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started
    daemon_reload: yes

- name: Ensure home assistant config folder exists
  file:
    path: /home/pi/homeassistant-config
    state: directory

- name: Ensure home assistant docker runs
  docker_container:
    name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    state: started
    network_mode: host
    restart_policy: unless-stopped
    devices:
      - "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2442422-if00:/dev/ttyConbeeII:rwm"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/homeassistant-config:/config

