- name: Ensure snapserver is downloaded
  get_url:
    url: https://deconz.dresden-elektronik.de/raspbian/beta/deconz-latest-beta.deb
    dest: '/home/pi/deconz-latest-beta.deb'
  register: downloaded_package
- name: Ensure snapserver is installed
  apt:
    deb: '{{downloaded_package.dest}}'
- name: Ensure snapserver service is enabled and started
  service:
    name: deconz 
    state: started
    enabled: yes
